import type { Metadata } from "next";
import localFont from "next/font/local";
import { Sidebar, ReactQueryProvider } from "@/components";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-full">
          <Sidebar />
          <ReactQueryProvider>
            <main className="h-full">
              <div className="ml-12 px-16 py-8 md:ml-32">{children}</div>
            </main>
          </ReactQueryProvider>
        </div>
      </body>
    </html>
  );
}
